type Post {
	id: ID!
	name: String!
	user: User!
}

input AddPostInput {
	name: String!
	userId: ID!
}

extend type Query {
	postList: [Post]
}

extend type Mutation {
	addPost(input: AddPostInput!): Post!
}
