type User {
	id: ID!
	name: String!
	posts: [Post]!
}

type Post {
	id: ID!
	name: String!
	user: User!
}

input AddUserInput {
	name: String!
	posts: [ID]
}

type Query {
	userList: [User]
}

type Mutation {
	addUser(input: AddUserInput): User!
}
