type User {
	id: ID!
	name: String!
	posts: [Post]!
}

input AddUserInput {
	name: String!
	posts: [ID]
}

extend type Query {
	userList: [User]
}

extend type Mutation {
	addUser(input: AddUserInput): User!
}
